services:
  nginx-foxio-lua:
    build: .
    container_name: nginx-foxio-lua
    ports:
      - "8455:443"
    volumes:
      - ./nginx.lua.conf:/etc/nginx/conf/nginx.conf:ro
      - ./lua:/etc/nginx/lua:ro
      - ./certs:/etc/nginx/certs:ro
    restart: unless-stopped
